<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PokemonTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('pokemon')->insert([
            [
                'pokemon' => 'Bulbasaur',
                'type1' => 'Grass',
                'type2' => 'Poison',
                'hp' => 45,
                'attack' => 49,
                'defense' => 49,
                'speed' => 45,
                'special' => 65,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/bulbasaur.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/bulbasaur.png',
                'description' => 'A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokemon.'
            ],
            [
                'pokemon' => 'Ivysaur',
                'type1' => 'Grass',
                'type2' => 'Poison',
                'hp' => 60,
                'attack' => 62,
                'defense' => 63,
                'speed' => 60,
                'special' => 80,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/ivysaur.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/ivysaur.png',
                'description' => 'Often seen swimming elegantly by lake shores. It is often mistaken for the Japanese monster, Kappa.'
            ],
            [
                'pokemon' => 'Venusaur',
                'type1' => 'Grass',
                'type2' => 'Poison',
                'hp' => 80,
                'attack' => 82,
                'defense' => 83,
                'speed' => 80,
                'special' => 100,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/venusaur.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/venusaur.png',
                'description' => 'Because it stores several kinds of toxic gases in its body, it is prone to exploding without warning.'
            ],
            [
                'pokemon' => 'Charmander',
                'type1' => 'Fire',
                'type2' => null,
                'hp' => 39,
                'attack' => 52,
                'defense' => 43,
                'speed' => 65,
                'special' => 50,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/charmander.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/charmander.png',
                'description' => 'Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail.'
            ],


            [
                'pokemon' => 'Charmeleon',
                'type1' => 'Fire',
                'type2' => null,
                'hp' => 58,
                'attack' => 64,
                'defense' => 58,
                'speed' => 80,
                'special' => 65,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/charmeleon.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/charmeleon.png',
                'description' => 'When it swings its burning tail, it elevates the temperature to unbearably high levels.'
            ],
            [
                'pokemon' => 'Charizard',
                'type1' => 'Fire',
                'type2' => 'Flying',
                'hp' => 78,
                'attack' => 84,
                'defense' => 78,
                'speed' => 100,
                'special' => 85,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/charizard.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/charizard.png',
                'description' => 'Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally.'
            ],
            [
                'pokemon' => 'Squirtle',
                'type1' => 'Water',
                'type2' => null,
                'hp' => 44,
                'attack' => 48,
                'defense' => 65,
                'speed' => 43,
                'special' => 50,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/squirtle.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/squirtle.png',
                'description' => 'After birth, its back swells and hardens into a shell. Powerfully sprays foam from its mouth.'
            ],
            [
                'pokemon' => 'Wartortle',
                'type1' => 'Water',
                'type2' => null,
                'hp' => 59,
                'attack' => 63,
                'defense' => 80,
                'speed' => 58,
                'special' => 65,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/wartortle.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/wartortle.png',
                'description' => 'Often hides in water to stalk unwary prey. For swimming fast, it moves its ears to maintain balance.'
            ],
            [
                'pokemon' => 'Blastoise',
                'type1' => 'Water',
                'type2' => null,
                'hp' => 79,
                'attack' => 83,
                'defense' => 100,
                'speed' => 78,
                'special' => 85,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/blastoise.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/blastoise.png',
                'description' => 'A brutal Pokemon with pressurized water jets on its shell. They are used for high-speed tackles.'
            ],
            [
                'pokemon' => 'Caterpie',
                'type1' => 'Bug',
                'type2' => null,
                'hp' => 45,
                'attack' => 30,
                'defense' => 35,
                'speed' => 45,
                'special' => 20,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/caterpie.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/caterpie.png',
                'description' => 'Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls.'
            ],
            [
                'pokemon' => 'Metapod',
                'type1' => 'Bug',
                'type2' => null,
                'hp' => 50,
                'attack' => 20,
                'defense' => 55,
                'speed' => 30,
                'special' => 25,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/metapod.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/metapod.png',
                'description' => 'This Pokemon is vulnerable to attack while its shell is soft, exposing its weak and tender body.'
            ],
            [
                'pokemon' => 'Butterfree',
                'type1' => 'Bug',
                'type2' => 'Flying',
                'hp' => 60,
                'attack' => 45,
                'defense' => 50,
                'speed' => 70,
                'special' => 80,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/butterfree.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/butterfree.png',
                'description' => 'In battle, it flaps its wings at high speed to release highly toxic dust into the air.'
            ],
            [
                'pokemon' => 'Weedle',
                'type1' => 'Bug',
                'type2' => 'Poison',
                'hp' => 40,
                'attack' => 35,
                'defense' => 30,
                'speed' => 50,
                'special' => 20,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/weedle.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/weedle.png',
                'description' => 'Often found in forests, eating leaves. It has a sharp venomous stinger on its head.'
            ],
            [
                'pokemon' => 'Kakuna',
                'type1' => 'Bug',
                'type2' => 'Poison',
                'hp' => 45,
                'attack' => 25,
                'defense' => 50,
                'speed' => 35,
                'special' => 25,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/kakuna.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/kakuna.png',
                'description' => 'Almost incapable of moving, this Pokemon can only harden its shell to protect itself from predators.'
            ],
            [
                'pokemon' => 'Beedrill',
                'type1' => 'Bug',
                'type2' => 'Poison',
                'hp' => 65,
                'attack' => 80,
                'defense' => 40,
                'speed' => 75,
                'special' => 45,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/beedrill.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/beedrill.png',
                'description' => 'Flies at high speed and attacks using its large venomous stingers on its forelegs and tail.'
            ],
            [
                'pokemon' => 'Pidgey',
                'type1' => 'Normal',
                'type2' => 'Flying',
                'hp' => 40,
                'attack' => 45,
                'defense' => 40,
                'speed' => 56,
                'special' => 35,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/pidgey.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/pidgey.png',
                'description' => 'A common sight in forests and woods. It flaps its wings at ground level to kick up blinding sand.'
            ],
            [
                'pokemon' => 'Pidgeotto',
                'type1' => 'Normal',
                'type2' => 'Flying',
                'hp' => 63,
                'attack' => 60,
                'defense' => 55,
                'speed' => 71,
                'special' => 50,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/pidgeotto.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/pidgeotto.png',
                'description' => 'Very protective of its sprawling territorial area, this Pokemon will fiercely peck at any intruder.'
            ],
            [
                'pokemon' => 'Pidgeot',
                'type1' => 'Normal',
                'type2' => 'Flying',
                'hp' => 83,
                'attack' => 80,
                'defense' => 75,
                'speed' => 91,
                'special' => 70,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/pidgeot.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/pidgeot.png',
                'description' => 'When hunting, it skims the surface of water at high speed to pick off unwary prey such as MAGIKARP.'
            ],
            [
                'pokemon' => 'Rattata',
                'type1' => 'Normal',
                'type2' => null,
                'hp' => 30,
                'attack' => 56,
                'defense' => 35,
                'speed' => 72,
                'special' => 25,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/rattata.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/rattata.png',
                'description' => 'Bites anything when it attacks. Small and very quick, it is a common sight in many places.'
            ],
            [
                'pokemon' => 'Raticate',
                'type1' => 'Normal',
                'type2' => null,
                'hp' => 55,
                'attack' => 81,
                'defense' => 60,
                'speed' => 97,
                'special' => 50,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/raticate.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/raticate.png',
                'description' => 'It uses its whiskers to maintain its balance. It apparently slows down if they are cut off.'
            ],
            [
                'pokemon' => 'Spearow',
                'type1' => 'Normal',
                'type2' => 'Flying',
                'hp' => 40,
                'attack' => 60,
                'defense' => 30,
                'speed' => 70,
                'special' => 31,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/spearow.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/spearow.png',
                'description' => 'Eats bugs in grassy areas. It has to flap its short wings at high speed to stay airborne.'
            ],
            [
                'pokemon' => 'Fearow',
                'type1' => 'Normal',
                'type2' => 'Flying',
                'hp' => 65,
                'attack' => 90,
                'defense' => 65,
                'speed' => 100,
                'special' => 61,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/fearow.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/fearow.png',
                'description' => 'With its huge and magnificent wings, it can keep aloft without ever having to land for rest.'
            ],
            [
                'pokemon' => 'Ekans',
                'type1' => 'Poison',
                'type2' => null,
                'hp' => 35,
                'attack' => 60,
                'defense' => 44,
                'speed' => 55,
                'special' => 40,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/ekans.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/ekans.png',
                'description' => 'The older it gets, the longer it grows. At night, it wraps its long body around tree branches to rest.'
            ],
            [
                'pokemon' => 'Arbok',
                'type1' => 'Poison',
                'type2' => null,
                'hp' => 60,
                'attack' => 95,
                'defense' => 69,
                'speed' => 80,
                'special' => 65,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/arbok.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/arbok.png',
                'description' => 'It is rumored that the ferocious warning markings on its belly differ from area to area.'
            ],
            [
                'pokemon' => 'Pikachu',
                'type1' => 'Electric',
                'type2' => null,
                'hp' => 35,
                'attack' => 55,
                'defense' => 40,
                'speed' => 90,
                'special' => 50,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/pikachu.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/pikachu.png',
                'description' => 'When several of these Pokémon gather, their electricity could build and cause lightning storms.'
            ],
            [
                'pokemon' => 'Raichu',
                'type1' => 'Electric',
                'type2' => null,
                'hp' => 60,
                'attack' => 90,
                'defense' => 55,
                'speed' => 100,
                'special' => 90,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/raichu.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/raichu.png',
                'description' => 'Its long tail serves as a ground to protect itself from its own high-voltage power.'
            ],
            [
                'pokemon' => 'Sandshrew',
                'type1' => 'Ground',
                'type2' => null,
                'hp' => 50,
                'attack' => 75,
                'defense' => 85,
                'speed' => 40,
                'special' => 30,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/sandshrew.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/sandshrew.png',
                'description' => 'Burrows deep underground in arid locations far from water. It only emerges to hunt for food.'
            ],
            [
                'pokemon' => 'Sandslash',
                'type1' => 'Ground',
                'type2' => null,
                'hp' => 75,
                'attack' => 100,
                'defense' => 110,
                'speed' => 65,
                'special' => 55,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/sandslash.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/sandslash.png',
                'description' => 'Curls up into a spiny ball when threatened. It can roll while curled up to attack or escape.'
            ],
            [
                'pokemon' => 'Nidoran♀',
                'type1' => 'Poison',
                'type2' => null,
                'hp' => 55,
                'attack' => 47,
                'defense' => 52,
                'speed' => 41,
                'special' => 40,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/nidoranf.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/nidoranf.png',
                'description' => 'Although small, its venomous barbs render this Pokémon dangerous. The female has smaller horns.'
            ],
            [
                'pokemon' => 'Nidorina',
                'type1' => 'Poison',
                'type2' => null,
                'hp' => 70,
                'attack' => 62,
                'defense' => 67,
                'speed' => 56,
                'special' => 55,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/nidorina.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/nidorina.png',
                'description' => 'The females horn develops slowly. Prefers physical attacks such as clawing and biting.'
            ],
            [
                'pokemon' => 'Nidoqueen',
                'type1' => 'Poison',
                'type2' => 'Ground',
                'hp' => 90,
                'attack' => 92,
                'defense' => 87,
                'speed' => 76,
                'special' => 75,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/nidoqueen.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/nidoqueen.png',
                'description' => 'Its hard scales provide strong protection. It uses its hefty bulk to execute powerful moves.'
            ],
            [
                'pokemon' => 'Nidoran♂',
                'type1' => 'Poison',
                'type2' => null,
                'hp' => 46,
                'attack' => 57,
                'defense' => 40,
                'speed' => 50,
                'special' => 40,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/nidoranm.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/nidoranm.png',
                'description' => 'Stiffens its ears to sense danger. The larger its horns, the more powerful its secreted venom.'
            ],
            [
                'pokemon' => 'Nidorino',
                'type1' => 'Poison',
                'type2' => null,
                'hp' => 61,
                'attack' => 72,
                'defense' => 57,
                'speed' => 65,
                'special' => 55,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/nidorino.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/nidorino.png',
                'description' => 'An aggressive Pokémon that is quick to attack. The horn on its head secretes a powerful venom.'
            ],
            [
                'pokemon' => 'Nidoking',
                'type1' => 'Poison',
                'type2' => 'Ground',
                'hp' => 81,
                'attack' => 102,
                'defense' => 77,
                'speed' => 85,
                'special' => 75,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/nidoking.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/nidoking.png',
                'description' => 'Its steel-like hide adds to its powerful tackle. Its horns are so hard, they can pierce a diamond.'
            ],

            [
                'pokemon' => 'Clefairy',
                'type1' => 'Normal',
                'type2' => 'Ground',
                'hp' => 70,
                'attack' => 45,
                'defense' => 48,
                'speed' => 35,
                'special' => 60,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/clefairy.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/clefairy.png',
                'description' => 'Its magical and cute appeal has many admirers. It is rare and found only in certain areas.'
            ],

            [
                'pokemon' => 'Clefable',
                'type1' => 'Normal',
                'type2' => null,
                'hp' => 95,
                'attack' => 70,
                'defense' => 73,
                'speed' => 60,
                'special' => 85,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/clefable.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/clefable.png',
                'description' => 'A timid fairy Pokemon that is rarely seen. It will run and hide the moment it senses people.'
            ],


            [
                'pokemon' => 'Vulpix',
                'type1' => 'Fire',
                'type2' => null,
                'hp' => 38,
                'attack' => 41,
                'defense' => 40,
                'speed' => 65,
                'special' => 65,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/vulpix.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/vulpix.png',
                'description' => 'At the time of birth, it has just one tail. The tail splits from its tip as it grows older.'
            ],
            [
                'pokemon' => 'Ninetales',
                'type1' => 'Fire',
                'type2' => null,
                'hp' => 73,
                'attack' => 76,
                'defense' => 75,
                'speed' => 100,
                'special' => 100,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/ninetales.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/ninetales.png',
                'description' => 'Very smart and very vengeful. Grabbing one of its many tails could result in a 1000-year curse.'
            ],
            [
                'pokemon' => 'Jigglypuff',
                'type1' => 'Normal',
                'type2' => null,
                'hp' => 115,
                'attack' => 45,
                'defense' => 20,
                'speed' => 20,
                'special' => 25,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/jigglypuff.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/jigglypuff.png',
                'description' => 'When its huge eyes light up, it sings a mysteriously soothing melody that lulls its enemies to sleep.',
            ],

            [
                'pokemon' => 'Wigglytuff',
                'type1' => 'Normal',
                'type2' => null,
                'hp' => 140,
                'attack' => 70,
                'defense' => 45,
                'speed' => 45,
                'special' => 50,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/wigglytuff.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/wigglytuff.png',
                'description' => 'The body is soft and rubbery. When angered, it will suck in air and inflate itself to an enormous size.',
            ],


            [
                'pokemon' => 'Zubat',
                'type1' => 'Poison',
                'type2' => 'Flying',
                'hp' => 40,
                'attack' => 45,
                'defense' => 35,
                'speed' => 55,
                'special' => 40,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/zubat.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/zubat.png',
                'description' => 'Forms colonies in perpetually dark places. Uses ultrasonic waves to identify and approach targets.',
            ],
            [
                'pokemon' => 'Golbat',
                'type1' => 'Poison',
                'type2' => 'Flying',
                'hp' => 75,
                'attack' => 80,
                'defense' => 70,
                'speed' => 90,
                'special' => 75,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/golbat.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/golbat.png',
                'description' => "Once it strikes, it will not stop draining energy from the victim even if it gets too heavy to fly.",
            ],
            [
                'pokemon' => 'Oddish',
                'type1' => 'Grass',
                'type2' => 'Poison',
                'hp' => 45,
                'attack' => 50,
                'defense' => 55,
                'speed' => 30,
                'special' => 75,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/oddish.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/oddish.png',
                'description' => 'During the day, it keeps its face buried in the ground. At night, it wanders around sowing its seeds.',
            ],
            [
                'pokemon' => 'Gloom',
                'type1' => 'Grass',
                'type2' => 'Poison',
                'hp' => 60,
                'attack' => 65,
                'defense' => 70,
                'speed' => 40,
                'special' => 85,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/gloom.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/gloom.png',
                'description' => 'The fluid that oozes from its mouth isn\'t drool. It is a nectar that is used to attract prey.',
            ],
            [
                'pokemon' => 'Vileplume',
                'type1' => 'Grass',
                'type2' => 'Poison',
                'hp' => 75,
                'attack' => 80,
                'defense' => 85,
                'speed' => 50,
                'special' => 100,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/vileplume.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/vileplume.png',
                'description' => 'The larger its petals, the more toxic pollen it contains. Its big head is heavy and hard to hold up.',
            ],
            [
                'pokemon' => 'Paras',
                'type1' => 'Bug',
                'type2' => 'Grass',
                'hp' => 35,
                'attack' => 70,
                'defense' => 55,
                'speed' => 25,
                'special' => 55,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/paras.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/paras.png',
                'description' => 'Burrows to suck tree roots. The mushrooms on its back grow by drawing nutrients from the bug host.',
            ],
            [
                'pokemon' => 'Parasect',
                'type1' => 'Bug',
                'type2' => 'Grass',
                'hp' => 60,
                'attack' => 95,
                'defense' => 80,
                'speed' => 30,
                'special' => 80,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/parasect.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/parasect.png',
                'description' => 'A host-parasite pair in which the parasite mushroom has taken over the host bug. Prefers damp places.',
            ],
            [
                'pokemon' => 'Venonat',
                'type1' => 'Bug',
                'type2' => 'Poison',
                'hp' => 60,
                'attack' => 55,
                'defense' => 50,
                'speed' => 45,
                'special' => 40,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/venonat.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/venonat.png',
                'description' => 'Lives in the shadows of tall trees where it eats insects. It is attracted by light at night.',
            ],
            [
                'pokemon' => 'Venomoth',
                'type1' => 'Bug',
                'type2' => 'Poison',
                'hp' => 70,
                'attack' => 65,
                'defense' => 60,
                'speed' => 90,
                'special' => 90,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/venomoth.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/venomoth.png',
                'description' => 'The dust-like scales covering its wings are color coded to indicate the kinds of poison it has.',
            ],
            [
                'pokemon' => 'Diglett',
                'type1' => 'Ground',
                'type2' => '',
                'hp' => 10,
                'attack' => 55,
                'defense' => 25,
                'speed' => 95,
                'special' => 45,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/diglett.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/diglett.png',
                'description' => 'Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.',
            ],

            [
                'pokemon' => 'Dugtrio',
                'type1' => 'Ground',
                'type2' => '',
                'hp' => 35,
                'attack' => 80,
                'defense' => 50,
                'speed' => 120,
                'special' => 70,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/dugtrio.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/dugtrio.png',
                'description' => 'A team of DIGLETT triplets. It triggers huge earthquakes by burrowing 60 miles underground.',
            ],
            [
                'pokemon' => 'Meowth',
                'type1' => 'Normal',
                'type2' => '',
                'hp' => 40,
                'attack' => 45,
                'defense' => 35,
                'speed' => 90,
                'special' => 40,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/meowth.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/meowth.png',
                'description' => 'Adores circular objects. Wanders the streets on a nightly basis to look for dropped loose change.',
            ],
            [
                'pokemon' => 'Persian',
                'type1' => 'Normal',
                'type2' => '',
                'hp' => 65,
                'attack' => 70,
                'defense' => 60,
                'speed' => 115,
                'special' => 65,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/persian.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/persian.png',
                'description' => 'Although its fur has many admirers, it is tough to raise as a pet because of its fickle meanness.',
            ],
            [
                'pokemon' => 'Psyduck',
                'type1' => 'Water',
                'type2' => '',
                'hp' => 50,
                'attack' => 52,
                'defense' => 48,
                'speed' => 55,
                'special' => 50,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/psyduck.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/psyduck.png',
                'description' => 'While lulling its enemies with its vacant look, this wily Pokemon will use psychokinetic powers.',
            ],
            [
                'pokemon' => 'Golduck',
                'type1' => 'Water',
                'type2' => '',
                'hp' => 80,
                'attack' => 82,
                'defense' => 78,
                'speed' => 85,
                'special' => 80,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/golduck.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/golduck.png',
                'description' => 'Often seen swimming elegantly by lake shores. It is often mistaken for the Japanese monster, Kappa.',
            ],
            [
                'pokemon' => 'Mankey',
                'type1' => 'Fighting',
                'type2' => '',
                'hp' => 40,
                'attack' => 80,
                'defense' => 35,
                'speed' => 70,
                'special' => 35,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/mankey.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/mankey.png',
                'description' => 'Extremely quick to anger. It could be docile one moment then thrashing away the next instant.',
            ],
            [
                'pokemon' => 'Primeape',
                'type1' => 'Fighting',
                'type2' => '',
                'hp' => 65,
                'attack' => 105,
                'defense' => 60,
                'speed' => 95,
                'special' => 60,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/primeape.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/primeape.png',
                'description' => 'Always furious and tenacious to boot. It will not abandon chasing its quarry until it is caught.',
            ],
            [
                'pokemon' => 'Growlithe',
                'type1' => 'Fire',
                'type2' => '',
                'hp' => 55,
                'attack' => 70,
                'defense' => 45,
                'speed' => 60,
                'special' => 50,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/growlithe.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/growlithe.png',
                'description' => 'Very protective of its territory. It will bark and bite to repel intruders from its space.',
            ],
            [
                'pokemon' => 'Arcanine',
                'type1' => 'Fire',
                'type2' => '',
                'hp' => 90,
                'attack' => 110,
                'defense' => 80,
                'speed' => 95,
                'special' => 80,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/arcanine.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/arcanine.png',
                'description' => 'A Pokemon that has been admired since the past for its beauty. It runs agilely as if on wings.',
            ],
            [
                'pokemon' => 'Poliwag',
                'type1' => 'Water',
                'type2' => '',
                'hp' => 40,
                'attack' => 50,
                'defense' => 40,
                'speed' => 90,
                'special' => 40,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/poliwag.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/poliwag.png',
                'description' => 'Its newly grown legs prevent it from running. It appears to prefer swimming than trying to stand.',
            ],
            [
                'pokemon' => 'Poliwhirl',
                'type1' => 'Water',
                'type2' => '',
                'hp' => 65,
                'attack' => 65,
                'defense' => 65,
                'speed' => 90,
                'special' => 50,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/poliwhirl.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/poliwhirl.png',
                'description' => 'Capable of living in or out of water. When out of water, it sweats to keep its body slimy.',
            ],
            [
                'pokemon' => 'Poliwrath',
                'type1' => 'Water',
                'type2' => 'Fighting',
                'hp' => 90,
                'attack' => 85,
                'defense' => 95,
                'speed' => 70,
                'special' => 70,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/poliwrath.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/poliwrath.png',
                'description' => 'An adept swimmer at both the front crawl and breast stroke. Easily overtakes the best human swimmers.',
            ],
            [
                'pokemon' => 'Abra',
                'type1' => 'Psychic',
                'type2' => '',
                'hp' => 25,
                'attack' => 20,
                'defense' => 15,
                'speed' => 90,
                'special' => 105,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/abra.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/abra.png',
                'description' => 'Using its ability to read minds, it will identify impending danger and TELEPORT to safety.',
            ],
            [
                'pokemon' => 'Kadabra',
                'type1' => 'Psychic',
                'type2' => '',
                'hp' => 40,
                'attack' => 35,
                'defense' => 30,
                'speed' => 105,
                'special' => 120,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/kadabra.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/kadabra.png',
                'description' => 'It emits special alpha waves from its body that induce headaches just by being close by.',
            ],
            [
                'pokemon' => 'Alakazam',
                'type1' => 'Psychic',
                'type2' => '',
                'hp' => 55,
                'attack' => 50,
                'defense' => 45,
                'speed' => 120,
                'special' => 135,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/alakazam.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/alakazam.png',
                'description' => 'Its brain can outperform a supercomputer. Its intelligence quotient is said to be 5,000.',
            ],
            [
                'pokemon' => 'Machop',
                'type1' => 'Fighting',
                'type2' => '',
                'hp' => 70,
                'attack' => 80,
                'defense' => 50,
                'speed' => 35,
                'special' => 35,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/machop.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/machop.png',
                'description' => 'Loves to build its muscles. It trains in all styles of martial arts to become even stronger.',
            ],
            [
                'pokemon' => 'Machoke',
                'type1' => 'Fighting',
                'type2' => '',
                'hp' => 80,
                'attack' => 100,
                'defense' => 70,
                'speed' => 45,
                'special' => 50,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/machoke.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/machoke.png',
                'description' => 'Its muscular body is so powerful, it must wear a power save belt to be able to regulate its motions.',
            ],

            [
                'pokemon' => 'Machamp',
                'type1' => 'Fighting',
                'type2' => '',
                'hp' => 90,
                'attack' => 130,
                'defense' => 80,
                'speed' => 55,
                'special' => 65,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/machamp.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/machamp.png',
                'description' => 'Using its heavy muscles, it throws powerful punches that can send the victim clear over the horizon.',
            ],
            [
                'pokemon' => 'Bellsprout',
                'type1' => 'Grass',
                'type2' => 'Poison',
                'hp' => 50,
                'attack' => 75,
                'defense' => 35,
                'speed' => 40,
                'special' => 70,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/bellsprout.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/bellsprout.png',
                'description' => 'A carnivorous Pokémon that traps and eats bugs. It uses its root feet to soak up needed moisture.',
            ],
            [
                'pokemon' => 'Weepinbell',
                'type1' => 'Grass',
                'type2' => 'Poison',
                'hp' => 65,
                'attack' => 90,
                'defense' => 50,
                'speed' => 55,
                'special' => 85,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/weepinbell.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/weepinbell.png',
                'description' => 'It spits out POISONPOWDER to immobilize the enemy and then finishes it with a spray of ACID.',
            ],
            [
                'pokemon' => 'Victreebel',
                'type1' => 'Grass',
                'type2' => 'Poison',
                'hp' => 80,
                'attack' => 105,
                'defense' => 65,
                'speed' => 70,
                'special' => 100,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/victreebel.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/victreebel.png',
                'description' => 'Said to live in huge colonies deep in jungles, although no one has ever returned from there.',
            ],
            [
                'pokemon' => 'Tentacool',
                'type1' => 'Water',
                'type2' => 'Poison',
                'hp' => 40,
                'attack' => 40,
                'defense' => 35,
                'speed' => 70,
                'special' => 100,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/tentacool.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/tentacool.png',
                'description' => 'Drifts in shallow seas. Anglers who hook them by accident are often punished by its stinging acid.',
            ], [
                'pokemon' => 'Tentacruel',
                'type1' => 'Water',
                'type2' => 'Poison',
                'hp' => 80,
                'attack' => 70,
                'defense' => 65,
                'speed' => 100,
                'special' => 120,
                'gif' => 'https://play.pokemonshowdown.com/sprites/bwani/tentacruel.gif',
                'png' => 'https://play.pokemonshowdown.com/sprites/bw/tentacruel.png',
                'description' => 'The tentacles are normally kept short. On hunts, they are extended to ensnare and immobilize prey.',
            ],
            [
                "pokemon" => "Geodude",
                "type1" => "Rock",
                "type2" => "Ground",
                "hp" => 40,
                "attack" => 80,
                "defense" => 100,
                "speed" => 20,
                "special" => 30,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/geodude.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/geodude.png",
                "description" => "Found in fields and mountains. Mistaking them for boulders, people often step or trip on them."
            ],
            [
                "pokemon" => "Graveler",
                "type1" => "Rock",
                "type2" => "Ground",
                "hp" => 55,
                "attack" => 95,
                "defense" => 115,
                "speed" => 35,
                "special" => 45,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/graveler.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/graveler.png",
                "description" => "Rolls down slopes to move. It rolls over any obstacle without slowing or changing its direction."
            ],
            [
                "pokemon" => "Golem",
                "type1" => "Rock",
                "type2" => "Ground",
                "hp" => 80,
                "attack" => 110,
                "defense" => 130,
                "speed" => 45,
                "special" => 55,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/golem.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/golem.png",
                "description" => "Its boulder-like body is extremely hard. It can easily withstand dynamite blasts without damage."
            ],
            [
                "pokemon" => "Ponyta",
                "type1" => "Fire",
                "type2" => null,
                "hp" => 50,
                "attack" => 85,
                "defense" => 55,
                "speed" => 90,
                "special" => 65,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/ponyta.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/ponyta.png",
                "description" => "Its hooves are 10 times harder than diamonds. It can trample anything completely flat in little time."
            ],
            [
                "pokemon" => "Rapidash",
                "type1" => "Fire",
                "type2" => null,
                "hp" => 65,
                "attack" => 100,
                "defense" => 70,
                "speed" => 105,
                "special" => 80,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/rapidash.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/rapidash.png",
                "description" => "Very competitive, this Pokemon will chase anything that moves fast in the hopes of racing it."
            ],
            [
                "pokemon" => "Slowpoke",
                "type1" => "Water",
                "type2" => "Psychic",
                "hp" => 90,
                "attack" => 65,
                "defense" => 65,
                "speed" => 15,
                "special" => 40,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/slowpoke.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/slowpoke.png",
                "description" => "Incredibly slow and dopey. It takes 5 seconds for it to feel pain when under attack."
            ],
            [
                "pokemon" => "Slowbro",
                "type1" => "Water",
                "type2" => "Psychic",
                "hp" => 95,
                "attack" => 75,
                "defense" => 110,
                "speed" => 30,
                "special" => 80,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/slowbro.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/slowbro.png",
                "description" => "The SHELLDER that is latched onto SLOWPOKE's tail is said to feed on the host's left over scraps."
            ],
            [
                "pokemon" => "Magnemite",
                "type1" => "Electric",
                "type2" => null,
                "hp" => 25,
                "attack" => 35,
                "defense" => 70,
                "speed" => 45,
                "special" => 95,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/magnemite.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/magnemite.png",
                "description" => "Uses anti-gravity to stay suspended. Appears without warning and uses THUNDER WAVE and similar moves."
            ],
            [
                "pokemon" => "Magneton",
                "type1" => "Electric",
                "type2" => null,
                "hp" => 50,
                "attack" => 60,
                "defense" => 95,
                "speed" => 70,
                "special" => 120,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/magneton.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/magneton.png",
                "description" => "Formed by several MAGNEMITEs linked together. They frequently appear when sunspots flare up."
            ],
            [
                "pokemon" => "Farfetch'd",
                "type1" => "Normal",
                "type2" => "Flying",
                "hp" => 52,
                "attack" => 65,
                "defense" => 55,
                "speed" => 60,
                "special" => 58,
                "gif" => "http://play.pokemonshowdown.com/sprites/bwani/farfetchd.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/farfetchd.png",
                "description" => "The sprig of green onions it holds is its weapon. It is used much like a metal sword."
            ],
            [
                "pokemon" => "Doduo",
                "type1" => "Normal",
                "type2" => "Flying",
                "hp" => 35,
                "attack" => 85,
                "defense" => 45,
                "speed" => 75,
                "special" => 35,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/doduo.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/doduo.png",
                "description" => "A bird that makes up for its poor flying with its fast foot speed. Leaves giant footprints."
            ],
            [
                "pokemon" => "Dodrio",
                "type1" => "Normal",
                "type2" => "Flying",
                "hp" => 60,
                "attack" => 110,
                "defense" => 70,
                "speed" => 100,
                "special" => 60,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/dodrio.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/dodrio.png",
                "description" => "Uses its three brains to execute complex plans. While two heads sleep, one head stays awake."
            ],
            [
                "pokemon" => "Seel",
                "type1" => "Water",
                "type2" => null,
                "hp" => 65,
                "attack" => 45,
                "defense" => 55,
                "speed" => 45,
                "special" => 70,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/seel.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/seel.png",
                "description" => "The protruding horn on its head is very hard. It is used for bashing through thick ice."
            ],
            [
                "pokemon" => "Dewgong",
                "type1" => "Water",
                "type2" => "Ice",
                "hp" => 90,
                "attack" => 70,
                "defense" => 80,
                "speed" => 70,
                "special" => 95,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/dewgong.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/dewgong.png",
                "description" => "Stores thermal energy in its body. Swims at a steady 8 knots even in intensely cold waters."
            ],
            [
                "pokemon" => "Grimer",
                "type1" => "Poison",
                "type2" => null,
                "hp" => 80,
                "attack" => 80,
                "defense" => 50,
                "speed" => 5,
                "special" => 40,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/grimer.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/grimer.png",
                "description" => "Appears in filthy areas. Thrives by sucking up polluted sludge that is pumped out of factories."
            ],
            [
                "pokemon" => "Muk",
                "type1" => "Poison",
                "type2" => null,

                "hp" => 105,
                "attack" => 105,
                "defense" => 75,
                "speed" => 50,
                "special" => 65,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/muk.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/muk.png",
                "description" => "Thickly covered with a filthy, vile sludge. It is so toxic, even its footprints contain poison."
            ],
            [
                "pokemon" => "Shellder",
                "type1" => "Water",
                "type2" => null,

                "hp" => 30,
                "attack" => 65,
                "defense" => 100,
                "speed" => 40,
                "special" => 45,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/shellder.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/shellder.png",
                "description" => "Its hard shell repels any kind of attack. It is vulnerable only when its shell is open."
            ],
            [
                "pokemon" => "Cloyster",
                "type1" => "Water",
                "type2" => "Ice",
                "hp" => 50,
                "attack" => 95,
                "defense" => 180,
                "speed" => 70,
                "special" => 85,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/cloyster.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/cloyster.png",
                "description" => "When attacked, it launches its horns in quick volleys. Its innards have never been seen."
            ],
            [
                "pokemon" => "Gastly",
                "type1" => "Ghost",
                "type2" => "Poison",
                "hp" => 30,
                "attack" => 35,
                "defense" => 30,
                "speed" => 80,
                "special" => 100,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/gastly.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/gastly.png",
                "description" => "Almost invisible, this gaseous Pokemon cloaks the target and puts it to sleep without notice."
            ],
            [
                "pokemon" => "Haunter",
                "type1" => "Ghost",
                "type2" => "Poison",
                "hp" => 45,
                "attack" => 50,
                "defense" => 45,
                "speed" => 95,
                "special" => 115,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/haunter.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/haunter.png",
                "description" => "Because of its ability to slip through block walls, it is said to be from another dimension."
            ],
            [
                "pokemon" => "Gengar",
                "type1" => "Ghost",
                "type2" => "Poison",
                "hp" => 60,
                "attack" => 65,
                "defense" => 60,
                "speed" => 110,
                "special" => 130,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/gengar.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/gengar.png",
                "description" => "Under a full moon, this Pokemon likes to mimic the shadows of people and laugh at their fright."
            ],
            [
                "pokemon" => "Onix",
                "type1" => "Rock",
                "type2" => "Ground",
                "hp" => 35,
                "attack" => 45,
                "defense" => 160,
                "speed" => 70,
                "special" => 30,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/onix.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/onix.png",
                "description" => "As it grows, the stone portions of its body harden to become similar to a diamond, but colored black."
            ],
            [
                "pokemon" => "Drowzee",
                "type1" => "Psychic",
                "type2" => null,
                "hp" => 60,
                "attack" => 48,
                "defense" => 45,
                "speed" => 42,
                "special" => 90,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/drowzee.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/drowzee.png",
                "description" => "Puts enemies to sleep then eats their dreams. Occasionally gets sick from eating bad dreams."
            ],
            [
                "pokemon" => "Hypno",
                "type1" => "Psychic",
                "type2" => null,
                "hp" => 85,
                "attack" => 73,
                "defense" => 70,
                "speed" => 67,
                "special" => 115,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/hypno.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/hypno.png",
                "description" => "When it locks eyes with an enemy, it will use a mix of PSI moves such as HYPNOSIS and CONFUSION."
            ],
            [
                "pokemon" => "Krabby",
                "type1" => "Water",
                "type2" => null,
                "hp" => 30,
                "attack" => 105,
                "defense" => 90,
                "speed" => 50,
                "special" => 25,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/krabby.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/krabby.png",
                "description" => "Its pincers are not only powerful weapons, they are used for balance when walking sideways."
            ],
            [
                "pokemon" => "Kingler",
                "type1" => "Water",
                "type2" => null,
                "hp" => 55,
                "attack" => 130,
                "defense" => 115,
                "speed" => 75,
                "special" => 50,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/kingler.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/kingler.png",
                "description" => "The large pincer has 10,000-horsepower strength. However, its huge size makes it unwieldy to use."
            ],
            [
                "pokemon" => "Voltorb",
                "type1" => "Electric",
                "type2" => null,
                "hp" => 40,
                "attack" => 30,
                "defense" => 50,
                "speed" => 100,
                "special" => 55,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/voltorb.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/voltorb.png",
                "description" => "Usually found in power plants. Easily mistaken for a Poké Ball, they have zapped many people."
            ],
            [
                "pokemon" => "Electrode",
                "type1" => "Electric",
                "type2" => null,
                "hp" => 60,
                "attack" => 50,
                "defense" => 70,
                "speed" => 140,
                "special" => 80,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/electrode.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/electrode.png",
                "description" => "It stores electric energy under very high pressure. It often explodes with little or no provocation."
            ],
            [
                "pokemon" => "Exeggcute",
                "type1" => "Grass",
                "type2" => "Psychic",
                "hp" => 60,
                "attack" => 40,
                "defense" => 80,
                "speed" => 40,
                "special" => 60,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/exeggcute.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/exeggcute.png",
                "description" => "Often mistaken for eggs. When disturbed, they quickly gather and attack in swarms."
            ],
            [
                "pokemon" => "Exeggutor",
                "type1" => "Grass",
                "type2" => "Psychic",
                "hp" => 95,
                "attack" => 95,
                "defense" => 85,
                "speed" => 55,
                "special" => 125,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/exeggutor.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/exeggutor.png",
                "description" => "Legend has it that on rare occasions, one of its heads will drop off and continue on as an EXEGGCUTE."
            ],




            [
                "pokemon" => "Cubone",
                "type1" => "Ground",
                "type2" => null,
                "hp" => 50,
                "attack" => 50,
                "defense" => 95,
                "speed" => 35,
                "special" => 40,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/cubone.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/cubone.png",
                "description" => "Because it never removes its skull helmet, no one has ever seen this Pokemon's real face."
            ],
            [
                "pokemon" => "Marowak",
                "type1" => "Ground",
                "type2" => null,
                "hp" => 60,
                "attack" => 80,
                "defense" => 110,
                "speed" => 45,
                "special" => 50,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/marowak.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/marowak.png",
                "description" => "The bone it holds is its key weapon. It throws the bone skillfully like a boomerang to KO targets."
            ],
            [
                "pokemon" => "Hitmonlee",
                "type1" => "Fighting",
                "type2" => null,
                "hp" => 50,
                "attack" => 120,
                "defense" => 53,
                "speed" => 87,
                "special" => 35,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/hitmonlee.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/hitmonlee.png",
                "description" => "When in a hurry, its legs lengthen progressively. It runs smoothly with extra long, loping strides."
            ],
            [
                "pokemon" => "Hitmonchan",
                "type1" => "Fighting",
                "type2" => null,
                "hp" => 50,
                "attack" => 105,
                "defense" => 79,
                "speed" => 76,
                "special" => 35,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/hitmonchan.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/hitmonchan.png",
                "description" => "While apparently doing nothing, it fires punches in lightning fast volleys that are impossible to see."
            ],
            [
                "pokemon" => "Lickitung",
                "type1" => "Normal",
                "type2" => null,
                "hp" => 90,
                "attack" => 55,
                "defense" => 75,
                "speed" => 30,
                "special" => 60,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/lickitung.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/lickitung.png",
                "description" => "Its tongue can be extended like a chameleon's. It leaves a tingling sensation when it licks enemies."
            ],
            [
                "pokemon" => "Koffing",
                "type1" => "Poison",
                "type2" => null,
                "hp" => 40,
                "attack" => 65,
                "defense" => 95,
                "speed" => 35,
                "special" => 60,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/koffing.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/koffing.png",
                "description" => "Because it stores several kinds of toxic gases in its body, it is prone to exploding without warning."
            ],
            [
                "pokemon" => "Weezing",
                "type1" => "Poison",
                "type2" => null,
                "hp" => 65,
                "attack" => 90,
                "defense" => 120,
                "speed" => 60,
                "special" => 85,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/weezing.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/weezing.png",
                "description" => "Where two kinds of poison gases meet, 2 KOFFINGs can fuse into a WEEZING over many years."
            ],
            [
                "pokemon" => "Rhyhorn",
                "type1" => "Ground",
                "type2" => "Rock",
                "hp" => 80,
                "attack" => 85,
                "defense" => 95,
                "speed" => 25,
                "special" => 30,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/rhyhorn.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/rhyhorn.png",
                "description" => "Its massive bones are 1000 times harder than human bones. It can easily knock a trailer flying."
            ],
            [
                "pokemon" => "Rhydon",
                "type1" => "Ground",
                "type2" => "Rock",
                "hp" => 105,
                "attack" => 130,
                "defense" => 120,
                "speed" => 40,
                "special" => 45,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/rhydon.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/rhydon.png",
                "description" => "Protected by an armor-like hide, it is capable of living in molten lava of 3,600 degrees."
            ],
            [
                "pokemon" => "Chansey",
                "type1" => "Normal",
                "type2" => null,
                "hp" => 250,
                "attack" => 5,
                "defense" => 5,
                "speed" => 50,
                "special" => 105,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/chansey.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/chansey.png",
                "description" => "A rare and elusive Pokemon that is said to bring happiness to those who manage to get it."
            ],
            [
                "pokemon" => "Tangela",
                "type1" => "Grass",
                "type2" => null,
                "hp" => 65,
                "attack" => 55,
                "defense" => 115,
                "speed" => 60,
                "special" => 100,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/tangela.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/tangela.png",
                "description" => "The whole body is swathed with wide vines that are similar to seaweed. Its vines shake as it walks."
            ],
            [
                "pokemon" => "Kangaskhan",
                "type1" => "Normal",
                "type2" => null,
                "hp" => 105,
                "attack" => 95,
                "defense" => 80,
                "speed" => 90,
                "special" => 40,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/kangaskhan.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/kangaskhan.png",
                "description" => "The infant rarely ventures out of its mother's protective pouch until it is 3 years old."
            ],
            [
                "pokemon" => "Horsea",
                "type1" => "Water",
                "type2" => null,
                "hp" => 30,
                "attack" => 40,
                "defense" => 70,
                "speed" => 60,
                "special" => 70,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/horsea.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/horsea.png",
                "description" => "Known to shoot down flying bugs with precision blasts of ink from the surface of the water."
            ],
            [
                "pokemon" => "Seadra",
                "type1" => "Water",
                "type2" => null,
                "hp" => 55,
                "attack" => 65,
                "defense" => 95,
                "speed" => 85,
                "special" => 95,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/seadra.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/seadra.png",
                "description" => "Capable of swimming backwards by rapidly flapping its wing-like pectoral fins and stout tail."
            ],
            [
                "pokemon" => "Goldeen",
                "type1" => "Water",
                "type2" => null,
                "hp" => 45,
                "attack" => 67,
                "defense" => 60,
                "speed" => 63,
                "special" => 50,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/goldeen.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/goldeen.png",
                "description" => "Its tail fin billows like an elegant ballroom dress, giving it the nickname of the Water Queen."
            ],
            [
                "pokemon" => "Seaking",
                "type1" => "Water",
                "type2" => null,
                "hp" => 80,
                "attack" => 92,
                "defense" => 65,
                "speed" => 68,
                "special" => 80,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/seaking.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/seaking.png",
                "description" => "In the autumn spawning season, they can be seen swimming powerfully up rivers and creeks."
            ],
            [
                "pokemon" => "Staryu",
                "type1" => "Water",
                "type2" => null,
                "hp" => 30,
                "attack" => 45,
                "defense" => 55,
                "speed" => 85,
                "special" => 70,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/staryu.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/staryu.png",
                "description" => "An enigmatic Pokemon that can effortlessly regenerate any appendage it loses in battle."
            ],
            [
                "pokemon" => "Starmie",
                "type1" => "Water",
                "type2" => "Psychic",
                "hp" => 60,
                "attack" => 75,
                "defense" => 85,
                "speed" => 115,
                "special" => 100,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/starmie.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/starmie.png",
                "description" => "Its central core glows with the seven colors of the rainbow. Some people value the core as a gem."
            ],
            [
                "pokemon" => "Mr. Mime",
                "type1" => "Psychic",
                "type2" => "Fairy",
                "hp" => 40,
                "attack" => 45,
                "defense" => 65,
                "speed" => 90,
                "special" => 100,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/mrmime.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/mrmime.png",
                "description" => "If interrupted while it is miming, it will slap around the offender with its broad hands."
            ],
            [
                "pokemon" => "Scyther",
                "type1" => "Bug",
                "type2" => "Flying",
                "hp" => 70,
                "attack" => 110,
                "defense" => 80,
                "speed" => 105,
                "special" => 55,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/scyther.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/scyther.png",
                "description" => "With ninja-like agility and speed, it can create the illusion that there is more than one."
            ],
            [
                "pokemon" => "Jynx",
                "type1" => "Ice",
                "type2" => "Psychic",
                "hp" => 65,
                "attack" => 50,
                "defense" => 35,
                "speed" => 95,
                "special" => 95,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/jynx.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/jynx.png",
                "description" => "It seductively wiggles its hips as it walks. It can cause people to dance in unison with it."
            ],
            [
                "pokemon" => "Electabuzz",
                "type1" => "Electric",
                "type2" => null,
                "hp" => 65,
                "attack" => 83,
                "defense" => 57,
                "speed" => 105,
                "special" => 85,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/electabuzz.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/electabuzz.png",
                "description" => "Normally found near power plants, they can wander away and cause major blackouts in cities."
            ],
            [
                "pokemon" => "Magmar",
                "type1" => "Fire",
                "type2" => null,
                "hp" => 65,
                "attack" => 95,
                "defense" => 57,
                "speed" => 93,
                "special" => 100,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/magmar.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/magmar.png",
                "description" => "Its body always burns with an orange glow that enables it to hide perfectly among flames."
            ],
            [
                "pokemon" => "Pinsir",
                "type1" => "Bug",
                "type2" => null,
                "hp" => 65,
                "attack" => 125,
                "defense" => 100,
                "speed" => 85,
                "special" => 55,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/pinsir.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/pinsir.png",
                "description" => "It grips prey with its pincers until the prey is torn in half. What it can't tear, it tosses far."
            ],
            [
                "pokemon" => "Tauros",
                "type1" => "Normal",
                "type2" => null,
                "hp" => 75,
                "attack" => 100,
                "defense" => 95,
                "speed" => 110,
                "special" => 70,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/tauros.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/tauros.png",
                "description" => "When it targets an enemy, it charges furiously while whipping its body with its long tails."
            ],
            [
                "pokemon" => "Magikarp",
                "type1" => "Water",
                "type2" => null,
                "hp" => 20,
                "attack" => 10,
                "defense" => 55,
                "speed" => 80,
                "special" => 20,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/magikarp.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/magikarp.png",
                "description" => "In the distant past, it was somewhat stronger than the horribly weak descendants that exist today."
            ],
            [
                "pokemon" => "Gyarados",
                "type1" => "Water",
                "type2" => "Flying",
                "hp" => 95,
                "attack" => 125,
                "defense" => 79,
                "speed" => 81,
                "special" => 100,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/gyarados.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/gyarados.png",
                "description" => "Rarely seen in the wild. Huge and vicious, it is capable of destroying entire cities in a rage."
            ],
            [
                "pokemon" => "Lapras",
                "type1" => "Water",
                "type2" => "Ice",
                "hp" => 130,
                "attack" => 85,
                "defense" => 80,
                "speed" => 60,
                "special" => 95,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/lapras.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/lapras.png",
                "description" => "Able to understand human speech and very intelligent, it loves to swim in the sea with people on its back."
            ],
            [
                "pokemon" => "Ditto",
                "type1" => "Normal",
                "type2" => null,
                "hp" => 48,
                "attack" => 48,
                "defense" => 48,
                "speed" => 48,
                "special" => 48,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/ditto.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/ditto.png",
                "description" => "It can freely recombine its own cellular structure to transform into other life-forms."
            ],
            [
                "pokemon" => "Eevee",
                "type1" => "Normal",
                "type2" => null,
                "hp" => 55,
                "attack" => 55,
                "defense" => 50,
                "speed" => 55,
                "special" => 65,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/eevee.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/eevee.png",
                "description" => "Its genetic code is unstable, so it could evolve in a variety of ways."
            ],
            [
                "pokemon" => "Vaporeon",
                "type1" => "Water",
                "type2" => null,
                "hp" => 130,
                "attack" => 65,
                "defense" => 60,
                "speed" => 65,
                "special" => 110,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/vaporeon.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/vaporeon.png",
                "description" => "Lives close to water. Its long tail is ridged with a fin which is often mistaken for a mermaid's."
            ],
            [
                "pokemon" => "Jolteon",
                "type1" => "Electric",
                "type2" => null,
                "hp" => 65,
                "attack" => 65,
                "defense" => 60,
                "speed" => 130,
                "special" => 110,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/jolteon.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/jolteon.png",
                "description" => "It accumulates negative ions in the atmosphere to blast out 10,000-volt lightning bolts."
            ],
            [
                "pokemon" => "Flareon",
                "type1" => "Fire",
                "type2" => null,
                "hp" => 65,
                "attack" => 130,
                "defense" => 60,
                "speed" => 65,
                "special" => 110,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/flareon.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/flareon.png",
                "description" => "When storing thermal energy in its body, its temperature could soar to over 1600 degrees."
            ],
            [
                "pokemon" => "Porygon",
                "type1" => "Normal",
                "type2" => null,
                "hp" => 65,
                "attack" => 60,
                "defense" => 70,
                "speed" => 40,
                "special" => 75,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/porygon.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/porygon.png",
                "description" => "A Pokemon that consists entirely of programming code. Capable of moving freely in cyberspace."
            ],
            [
                "pokemon" => "Omanyte",
                "type1" => "Rock",
                "type2" => "Water",
                "hp" => 35,
                "attack" => 40,
                "defense" => 100,
                "speed" => 35,
                "special" => 90,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/omanyte.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/omanyte.png",
                "description" => "Although long extinct, in rare cases, it can be genetically resurrected from fossils."
            ],
            [
                "pokemon" => "Omastar",
                "type1" => "Rock",
                "type2" => "Water",
                "hp" => 70,
                "attack" => 60,
                "defense" => 125,
                "speed" => 55,
                "special" => 115,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/omastar.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/omastar.png",
                "description" => "A prehistoric Pokemon that died out when its heavy shell made it impossible to catch prey."
            ],
            [
                "pokemon" => "Kabuto",
                "type1" => "Rock",
                "type2" => "Water",
                "hp" => 30,
                "attack" => 80,
                "defense" => 90,
                "speed" => 55,
                "special" => 55,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/kabuto.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/kabuto.png",
                "description" => "A Pokemon that was resurrected from a fossil. It lived in the sea and hunted with claws."
            ],
            [
                "pokemon" => "Kabutops",
                "type1" => "Rock",
                "type2" => "Water",
                "hp" => 60,
                "attack" => 115,
                "defense" => 105,
                "speed" => 80,
                "special" => 70,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/kabutops.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/kabutops.png",
                "description" => "It is thought that this Pokemon became extinct because its spiral-shaped shell grew too large."
            ],
            [
                "pokemon" => "Aerodactyl",
                "type1" => "Rock",
                "type2" => "Flying",
                "hp" => 80,
                "attack" => 105,
                "defense" => 65,
                "speed" => 130,
                "special" => 60,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/aerodactyl.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/aerodactyl.png",
                "description" => "A ferocious, prehistoric Pokemon that goes for the enemy's throat with its serrated, sawlike fangs."
            ],
            [
                "pokemon" => "Snorlax",
                "type1" => "Normal",
                "type2" => null,
                "hp" => 160,
                "attack" => 110,
                "defense" => 65,
                "speed" => 30,
                "special" => 65,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/snorlax.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/snorlax.png",
                "description" => "Very lazy. Just eats and sleeps. As its rotund bulk builds, it becomes steadily more slothful."
            ],
            [
                "pokemon" => "Articuno",
                "type1" => "Ice",
                "type2" => "Flying",
                "hp" => 90,
                "attack" => 85,
                "defense" => 100,
                "speed" => 85,
                "special" => 125,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/articuno.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/articuno.png",
                "description" => "A legendary bird Pokemon. It can create blizzards by freezing moisture in the air."
            ],
            [
                "pokemon" => "Zapdos",
                "type1" => "Electric",
                "type2" => "Flying",
                "hp" => 90,
                "attack" => 90,
                "defense" => 85,
                "speed" => 100,
                "special" => 125,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/zapdos.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/zapdos.png",
                "description" => "A legendary bird Pokemon that is said to appear from clouds while dropping enormous lightning bolts."
            ],
            [
                "pokemon" => "Moltres",
                "type1" => "Fire",
                "type2" => "Flying",
                "hp" => 90,
                "attack" => 100,
                "defense" => 90,
                "speed" => 90,
                "special" => 125,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/moltres.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/moltres.png",
                "description" => "Known as the legendary bird of fire. Every flap of its wings creates a dazzling flash of flames."
            ],
            [
                "pokemon" => "Dratini",
                "type1" => "Dragon",
                "type2" => null,
                "hp" => 41,
                "attack" => 64,
                "defense" => 45,
                "speed" => 50,
                "special" => 50,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/dratini.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/dratini.png",
                "description" => "Long considered a mythical Pokemon until recently when a small colony was found living underwater."
            ],
            [
                "pokemon" => "Dragonair",
                "type1" => "Dragon",
                "type2" => null,
                "hp" => 61,
                "attack" => 84,
                "defense" => 65,
                "speed" => 70,
                "special" => 70,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/dragonair.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/dragonair.png",
                "description" => "A mystical Pokemon that exudes a gentle aura. Has the ability to change climate conditions."
            ],
            [
                "pokemon" => "Dragonite",
                "type1" => "Dragon",
                "type2" => "Flying",
                "hp" => 91,
                "attack" => 134,
                "defense" => 95,
                "speed" => 80,
                "special" => 100,
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/dragonite.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/dragonite.png",
                "description" => "An extremely rarely seen marine Pokemon. Its intelligence is said to match that of humans."
            ],
            [
                "pokemon" => "Mewtwo",
                "type1" => "Psychic",
                "type2" => null,
                "hp" => "106",
                "attack" => "110",
                "defense" => "90",
                "speed" => "130",
                "special" => "154",
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/mewtwo.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/mewtwo.png",
                "description" => "It was created by a scientist after years of horrific gene splicing and DNA engineering experiments."
            ],
            [
                "pokemon" => "Mew",
                "type1" => "Psychic",
                "type2" => null,
                "hp" => "100",
                "attack" => "100",
                "defense" => "100",
                "speed" => "100",
                "special" => "100",
                "gif" => "https://play.pokemonshowdown.com/sprites/bwani/mew.gif",
                "png" => "https://play.pokemonshowdown.com/sprites/bw/mew.png",
                "description" => "So rare that it is still said to be a mirage by many experts. Only a few people have seen it worldwide."
            ]

        ]);
    }
}
